# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "centos65"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "chef/site-cookbooks/"
    chef.add_recipe "yum"
    chef.add_recipe "git"
    chef.add_recipe "node"
    chef.add_recipe "ruby"
    # chef.add_recipe "ruby::gem"
  end

  config.omnibus.chef_version = :latest
end
