# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos65"

  config.vm.network "private_network", ip: "192.168.33.17"

  # SSH Keys
  config.ssh.forward_agent = true

  # Ansible
  config.vm.provision :ansible do |a|
    a.playbook = 'main.yml'
    a.inventory_path = 'hosts'
    a.limit = 'all'
  end
end
