development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  backlog_client_id: <%= ENV["BACKLOG_CLIENT_ID"] %>
  backlog_client_secret: <%= ENV["BACKLOG_CLIENT_SECRET"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  backlog_client_id: <%= ENV["BACKLOG_CLIENT_ID"] %>
  backlog_client_secret: <%= ENV["BACKLOG_CLIENT_SECRET"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  backlog_client_id: <%= ENV["BACKLOG_CLIENT_ID"] %>
  backlog_client_secret: <%= ENV["BACKLOG_CLIENT_SECRET"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

