development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  backlog_client_id: <%= ENV["BACKLOG_CLIENT_ID"] %>
  backlog_client_secret: <%= ENV["BACKLOG_CLIENT_SECRET"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  backlog_client_id: <%= ENV["BACKLOG_CLIENT_ID"] %>
  backlog_client_secret: <%= ENV["BACKLOG_CLIENT_SECRET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  backlog_client_id: <%= ENV["BACKLOG_CLIENT_ID"] %>
  backlog_client_secret: <%= ENV["BACKLOG_CLIENT_SECRET"] %>

