- name: install requires
  sudo: true
  yum: name={{ item }} enablerepo=centosplus state=present
  with_items:
    - "{{ ruby_requires }}"

- name: install requires
  sudo: true
  yum: name=readline-devel state=present

- name: rbenv | update rbenv repo
  sudo: true
  git: repo=git://github.com/sstephenson/rbenv.git dest={{ rbenv_root }} version=v0.4.0 accept_hostkey=yes

- name: rbenv | add rbenv to path
  sudo: true
  file: path=/usr/local/bin/rbenv src={{ rbenv_root }}/bin/rbenv state=link

- name: rbenv | add rbenv initialization to profile
  sudo: true
  template: src=rbenv.sh.j2 dest=/etc/profile.d/rbenv.sh owner=root group=root mode=0755

- name: rbenv | check ruby-build installed
  command: test -x /usr/local/bin/ruby-build
  register: rbuild_present
  ignore_errors: yes

- name: rbenv | create temporary directory
  command: mktemp -d
  register: tempdir
  when: rbuild_present|failed

- name: rbenv | clone ruby-build repo
  sudo: true
  git: repo=git://github.com/sstephenson/ruby-build.git dest={{tempdir.stdout}}/ruby-build accept_hostkey=yes
  when: rbuild_present|failed

- name: rbenv | install ruby-build
  sudo: true
  command: ./install.sh chdir={{tempdir.stdout}}/ruby-build
  when: rbuild_present|failed

- name: rbenv | remove temporary directory
  sudo: true
  file: path={{tempdir.stdout}} state=absent
  when: rbuild_present|failed

- name: rbenv | check ruby ruby_version installed
  shell: RBENV_ROOT={{rbenv_root}} rbenv versions | grep {{ruby_version}}
  register: ruby_installed
  ignore_errors: yes

- name: rbenv | create shims dir
  sudo: yes
  file: path={{ rbenv_root }}/shims state=directory
  when: ruby_installed|failed

- name: rbenv | create versions dir
  sudo: yes
  file: path={{ rbenv_root }}/versions state=directory
  when: ruby_installed|failed

- name: rbenv | change owner of install dir
  sudo: yes
  command: chgrp -R vagrant {{ rbenv_root }}
  when: ruby_installed|failed

- name: rbenv | change mode of install dir
  sudo: yes
  command: chmod -R g+rwxXs {{ rbenv_root }}
  when: ruby_installed|failed

- name: rbenv | install ruby ruby_version
  shell: RBENV_ROOT={{rbenv_root}} rbenv install {{ruby_version}}
  when: ruby_installed|failed

- name: rbenv | set global ruby {{ruby_version}}
  shell: RBENV_ROOT={{rbenv_root}} rbenv global {{ruby_version}}
  when: ruby_installed|failed

- name: rbenv | rehash
  shell: RBENV_ROOT={{rbenv_root}} rbenv rehash
  when: ruby_installed|failed
